# Generated by Django 4.2.2 on 2023-06-26 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('note', models.TextField(null=True)),
                ('joined_at', models.DateField(null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='members.company')),
            ],
        ),
    ]
